### ISSUE TITLE
Support short lived containers

### ISSUE THREAD

**Issue by mwl** [ContainerSolutions/minimesos#121]
Some containers dies a natural death before the test finish, but it leads to a stack trace in the log

```
    [ERROR] 2015-10-22 10:49:06,087 org.apache.mesos.mini.container.AbstractContainer remove - Could not remove container elasticsearch-scheduler_-1274157263
    com.github.dockerjava.api.NotFoundException: no such id: f6c22b85d073813466a34050c4df2913eaeecbaa2dcac2110a32537dbfe04c28

      at com.github.dockerjava.core.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:48)
      at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
      at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
      at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
      at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
      at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
      at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
      at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
      at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
      at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:399)
      at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:348)
      at com.github.dockerjava.jaxrs.RemoveContainerCmdExec.execute(RemoveContainerCmdExec.java:26)
      at com.github.dockerjava.jaxrs.RemoveContainerCmdExec.execute(RemoveContainerCmdExec.java:11)
      at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
      at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
      at com.github.dockerjava.core.command.RemoveContainerCmdImpl.exec(RemoveContainerCmdImpl.java:77)
      at org.apache.mesos.mini.container.AbstractContainer.remove(AbstractContainer.java:113)
      at org.apache.mesos.mini.MesosCluster.stop(MesosCluster.java:81)
      at org.apache.mesos.elasticsearch.systemtest.FrameworkRoleSystemTest.after(FrameworkRoleSystemTest.java:46)
```

**Comment by sadovnikov** [comment]
Is not reproducible today. 

* Started `com.containersolutions.mesoshelloworld.docker.systemtest.DiscoverySystemTest` with a breakpoint
* when stopped, killed `containersol/mesos-hello-world-scheduler` container
* continued the run

Cluster was removed without error traces.

Please, reopen the ticket if exception traces is still seen under other circumstances
