### ISSUE TITLE
Unable to switch to 0.27.0-0.2.190.ubuntu1404 images

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#282]
Attempts to switch results in multiple unit test failures

![image](https://cloud.githubusercontent.com/assets/4749332/13602951/262c7662-e53a-11e5-9c08-7c0dfa39ff16.png)

**Comment by frankscholten** [comment]
Which unit tests? If the container does not start it should show the logs. Another problem could be that pulling takes too long and the process times out.

**Comment by sadovnikov** [comment]
`CommandTest` and others. 9 tests in total

```
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:146)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at com.containersol.minimesos.mesos.MesosContainer.getStateInfoJSON(MesosContainer.java:91)
	at com.containersol.minimesos.cluster.MesosCluster.lambda$waitForState$3(MesosCluster.java:424)
	at com.containersol.minimesos.cluster.MesosCluster$$Lambda$43/1766099855.call(Unknown Source)
	at com.jayway.awaitility.core.CallableCondition$ConditionEvaluationWrapper.call(CallableCondition.java:100)
	at com.jayway.awaitility.core.CallableCondition$ConditionEvaluationWrapper.call(CallableCondition.java:85)
	at com.jayway.awaitility.core.ConditionAwaiter$1.run(ConditionAwaiter.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:102)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:142)
	... 14 more
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:93)
	... 15 more
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:105)
	at org.json.JSONArray.<init>(JSONArray.java:144)
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
	... 16 more
```

**Comment by sadovnikov** [comment]
In `0.27` version of Mesos state.json contains duplicated attribute
![image](https://cloud.githubusercontent.com/assets/4749332/13630692/e37df7ee-e5e0-11e5-8207-4643954643e5.png)
Used by `com.mashape.unirest.request.GetRequest` seems to treat this attribute as an array and therefore does not accept the value format

**Comment by frankscholten** [comment]
Duplicate active fields is caused by a bug in Mesos 0.27.0 https://issues.apache.org/jira/browse/MESOS-4582
