### ISSUE TITLE
Failures to write from containers to host

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#426]
Map mesos sandboxes to host using `minimesos` cluster configuration
```
    clusterName = "ELK Demo Cluster"
    loggingLevel = "INFO"
    mapAgentSandboxVolume = true
    mesosVersion = "0.25"
    timeout = 60
```

Install ES framework using 
```
{
  "id": "elasticsearch",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler:1.0.1",
      "network": "BRIDGE"
    }
  },
  "args": [
    "--zookeeperMesosUrl", "${MINIMESOS_ZOOKEEPER}",
    "--useIpAddress", "true",
    "--frameworkUseDocker", "false"
  ],
  "cpus": 0.2,
  "mem": 512.0,
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "instances": 1
}
```

`elasticsearch-executor` fails with
```
log4j:ERROR Either File or DatePattern options are not set for appender [index_indexing_slow_log_file].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /tmp/mesos/slaves/3e2e3ea9-27bf-40ad-b66f-4d366c176adc-S1/frameworks/3e2e3ea9-27bf-40ad-b66f-4d366c176adc-0001/executors/elasticsearch_172.17.0.6_20160504T091443.695Z/runs/82e7cea3-2dfe-4963-bbcb-31d45ea9144a/es_home/logs/mesos-ha_index_search_slowlog.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:128)
	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:204)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:258)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
log4j:ERROR Either File or DatePattern options are not set for appender [index_search_slow_log_file].
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.home' (es_home/bin)
Likely root cause: java.nio.file.AccessDeniedException: /tmp/mesos/slaves/3e2e3ea9-27bf-40ad-b66f-4d366c176adc-S1/frameworks/3e2e3ea9-27bf-40ad-b66f-4d366c176adc-0001/executors/elasticsearch_172.17.0.6_20160504T091443.695Z/runs/82e7cea3-2dfe-4963-bbcb-31d45ea9144a/es_home
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:243)
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
```

Everything is fine with `mapAgentSandboxVolume = false`

**Comment by sadovnikov** [comment]
Possibly, has the same cause as #427
