### ISSUE TITLE
Stacktrace when adding non-existing flags to minimesos subcommand

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#428]
```
frank@franktop:~/src/exercises$ minimesos destroy --marathonFile es.json 
Failed to parse parameters. Unknown option: --marathonFile

Exception in thread "main" java.lang.NullPointerException
	at com.beust.jcommander.JCommander.usage(JCommander.java:1134)
	at com.beust.jcommander.JCommander.usage(JCommander.java:1049)
	at com.containersol.minimesos.main.Main.printUsage(Main.java:139)
	at com.containersol.minimesos.main.Main.run(Main.java:88)
	at com.containersol.minimesos.main.Main.main(Main.java:55
```

**Comment by sadovnikov** [comment]
It's not reproducible with latest version in `master`. Let's test again after releasing `0.8.1`
