### ISSUE TITLE
Unable to run on docker 1.12

### ISSUE THREAD

**Issue by alde** [ContainerSolutions/minimesos#465]
Running on Docker 1.12 results in

```bash
$ minimesos up
Exception in thread "main" com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
        at com.containersol.minimesos.container.AbstractContainer.start(AbstractContainer.java:93)
        at com.containersol.minimesos.cluster.MesosCluster.lambda$start$0(MesosCluster.java:126)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.containersol.minimesos.cluster.MesosCluster.start(MesosCluster.java:126)
        at com.containersol.minimesos.cluster.MesosCluster.start(MesosCluster.java:112)
        at com.containersol.minimesos.main.CommandUp.execute(CommandUp.java:104)
        at com.containersol.minimesos.main.Main.run(Main.java:125)
        at com.containersol.minimesos.main.Main.main(Main.java:56)
```

Using native osx docker beta 
```bash
$ docker --version
Docker version 1.12.0-rc2, build 906eacd, experimental
```

**Comment by adam-sandor** [comment]
Thanks for the report @alde! We'll investigate soon.

**Comment by frankscholten** [comment]
This will be fixed in https://github.com/ContainerSolutions/minimesos/issues/469

**Comment by frankscholten** [comment]
Fixed by https://github.com/ContainerSolutions/minimesos/pull/470

**Comment by alde** [comment]
Thanks!

**Comment by frankscholten** [comment]
Reopening because of extra changes in
