### ISSUE TITLE
Exception thrown when minimesos up for the first time

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#484]
```
$ minimesos up
Exception in thread "main" com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
        at com.containersol.minimesos.container.AbstractContainer.start(AbstractContainer.java:93)
        at com.containersol.minimesos.cluster.MesosCluster.lambda$start$0(MesosCluster.java:126)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.containersol.minimesos.cluster.MesosCluster.start(MesosCluster.java:126)
        at com.containersol.minimesos.cluster.MesosCluster.start(MesosCluster.java:112)
        at com.containersol.minimesos.main.CommandUp.execute(CommandUp.java:104)
        at com.containersol.minimesos.main.Main.run(Main.java:125)
        at com.containersol.minimesos.main.Main.main(Main.java:56)
```

Docker version
```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:39:43 2016
 OS/Arch:      linux/amd64
```

Docker info
```
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-boot2docker
Operating System: Boot2Docker 1.12.0-rc4 (TCL 7.2); HEAD : cbe6927 - Wed Jul 13 14:19:29 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: dev
ID: N4CK:ELKF:X74H:EPSA:ZGVJ:4YME:WJ2W:BUHY:I7PJ:S7IQ:J6R5:IRSE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 25
 System Time: 2016-07-19T14:32:31.640788208Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Comment by frankscholten** [comment]
@alex-glv This is fixed by https://github.com/ContainerSolutions/minimesos/issues/465 and will be part of 0.9.1.
