### ISSUE TITLE
NPE in MesosCluster

### ISSUE THREAD

**Issue by pschorf** [ContainerSolutions/minimesos#532]
I'm getting this stack trace with 0.13.0 running minimesos up on a minimesosFile without marathon:

java.lang.NullPointerException
    at com.containersol.minimesos.cluster.MesosCluster.<init>(MesosCluster.java:109)
    at com.containersol.minimesos.cluster.MesosCluster.loadCluster(MesosCluster.java:79)
    at com.containersol.minimesos.cluster.ClusterRepository.loadCluster(ClusterRepository.java:31)
    at com.containersol.minimesos.main.CommandUp.getCluster(CommandUp.java:131)
    at com.containersol.minimesos.main.CommandUp.execute(CommandUp.java:73)
    at com.containersol.minimesos.main.Main.run(Main.java:108)
    at com.containersol.minimesos.main.Main.main(Main.java:60)

I think the culprit is this line: https://github.com/ContainerSolutions/minimesos/blob/master/minimesos/src/main/java/com/containersol/minimesos/cluster/MesosCluster.java#L109 which assumes that there's a marathon.

**Comment by frankscholten** [comment]
@pschorf Thanks for spotting this one! Indeed Marathon is currently optional but really it should be required since the `install` command depends on it.
